-- ============================================================
-- Goyenda — cases table, storage buckets, RLS
--
-- Run once in the Supabase dashboard: SQL Editor → New query → paste → Run.
-- Safe to re-run: every statement is idempotent.
-- ============================================================

-- ------------------------------------------------------------
-- 1. cases
-- ------------------------------------------------------------
create table if not exists public.cases (
  id              uuid primary key default gen_random_uuid(),

  -- Stable display number for "CASE 007". Never reused, never reordered.
  -- `position` is what the catalogue sorts by; this is what it prints.
  case_number     integer generated by default as identity unique,

  slug            text not null unique
                  check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title           text not null check (length(title) between 1 and 120),

  -- One-liner on cards. Two-to-three-sentence teaser on the detail page.
  premise         text not null default '',
  description     text not null default '',

  price           integer not null default 0 check (price >= 0),        -- BDT
  difficulty_rank text not null default 'rookie'
                  check (difficulty_rank in ('rookie', 'senior', 'master')),

  position        integer not null default 0,   -- catalogue order, ascending
  published       boolean not null default false,
  featured        boolean not null default false, -- homepage teaser row

  thumbnail_url   text,                           -- public URL, case-media bucket
  gallery_urls    text[] not null default '{}',   -- public URLs, ordered

  case_pdf_path     text,                         -- object path, case-files bucket
  solution_pdf_path text,                         -- object path, case-files bucket

  tags            text[] not null default '{}',
  solve_minutes   integer not null default 60 check (solve_minutes > 0),
  page_count      integer not null default 0 check (page_count >= 0),

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists cases_position_idx  on public.cases (position, created_at);
create index if not exists cases_published_idx on public.cases (published) where published;

-- Keep updated_at honest.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists cases_set_updated_at on public.cases;
create trigger cases_set_updated_at
  before update on public.cases
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 2. Row Level Security
--
-- Two roles matter:
--   anon           — the public site, reading with the anon key
--   authenticated  — the one admin user, signed in via Supabase Auth
--
-- Sign-ups are disabled in the dashboard (Authentication → Providers →
-- Email → "Allow new users to sign up" OFF), so "authenticated" means
-- "the admin". If that ever changes, tighten these to an allow-list.
-- ------------------------------------------------------------
alter table public.cases enable row level security;

drop policy if exists "public reads published cases" on public.cases;
create policy "public reads published cases"
  on public.cases for select
  to anon, authenticated
  using (published = true);

drop policy if exists "admin reads all cases" on public.cases;
create policy "admin reads all cases"
  on public.cases for select
  to authenticated
  using (true);

drop policy if exists "admin inserts cases" on public.cases;
create policy "admin inserts cases"
  on public.cases for insert
  to authenticated
  with check (true);

drop policy if exists "admin updates cases" on public.cases;
create policy "admin updates cases"
  on public.cases for update
  to authenticated
  using (true) with check (true);

drop policy if exists "admin deletes cases" on public.cases;
create policy "admin deletes cases"
  on public.cases for delete
  to authenticated
  using (true);

-- ------------------------------------------------------------
-- 3. Storage buckets
--
--   case-media  PUBLIC   thumbnails + gallery images; URLs go straight
--                        into <img src>. 5 MB cap, images only.
--   case-files  PRIVATE  case PDFs + solution PDFs. Only ever served via
--                        short-lived signed URLs after purchase. 50 MB cap.
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('case-media', 'case-media', true,  5242880,  array['image/jpeg','image/png','image/webp','image/avif']),
  ('case-files', 'case-files', false, 52428800, array['application/pdf'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- storage.objects already has RLS on. Policies:

-- case-media: anyone reads, admin writes.
drop policy if exists "anyone reads case-media" on storage.objects;
create policy "anyone reads case-media"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'case-media');

drop policy if exists "admin inserts case-media" on storage.objects;
create policy "admin inserts case-media"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'case-media');

drop policy if exists "admin updates case-media" on storage.objects;
create policy "admin updates case-media"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'case-media');

drop policy if exists "admin deletes case-media" on storage.objects;
create policy "admin deletes case-media"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'case-media');

-- case-files: admin only, full access. Buyers will get signed URLs
-- minted server-side later; no anon policy on purpose.
drop policy if exists "admin reads case-files" on storage.objects;
create policy "admin reads case-files"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'case-files');

drop policy if exists "admin inserts case-files" on storage.objects;
create policy "admin inserts case-files"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'case-files');

drop policy if exists "admin updates case-files" on storage.objects;
create policy "admin updates case-files"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'case-files');

drop policy if exists "admin deletes case-files" on storage.objects;
create policy "admin deletes case-files"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'case-files');
